=encoding euc-jp

=head1 Name

CGI::Application::Plugin::Eparam::Nihongo

=head1 SYNOPSIS

    package WebApp
    use Jcode;# &#12371;&#12398;&#20182; use Encode &#12377;&#12427;&#12363;&#12289;&#33258;&#21069;&#12391; $CGI::Application::Plugin::Eparam::econv = sub { ... } &#12392;&#12289;&#22793;&#25563;&#12525;&#12472;&#12483;&#12463;&#12434;&#23455;&#35013;&#12377;&#12427;
    use CGI::Application::Plugin::Eparam;
    sub cgiapp_init {
            $CGI::Application::Plugin::Eparam::icode = 'sjis';   # &#20837;&#21147;&#12373;&#12428;&#12427;&#25991;&#23383;&#12467;&#12540;&#12489;
            $CGI::Application::Plugin::Eparam::ocode = 'euc-jp'; # &#22793;&#25563;&#12375;&#12383;&#12356;&#25991;&#23383;&#12467;&#12540;&#12489;
    }
    package WebApp::Pages::Public
    sub page1 {
            my $self = shift;
            my $data = $self->eparam('data');               # &#22793;&#25563;&#24460;&#12398;&#20516;
            my $natural_data = $self->query->param('data'); # &#22793;&#25563;&#21069;&#12398;&#20516;
    }

=head1 Example

=head2 Get Value

    package WebApp::Pages::Public
    sub page1 {
            my $self = shift;
            my $data = $self->eparam('data');
            my $natural_data = $self->query->param('data');
    }

=head2 in Application

    package WebApp
    use Jcode;
    use CGI::Application::Plugin::Eparam;
    sub cgiapp_init {
            $CGI::Application::Plugin::Eparam::icode = 'sjis';
            $CGI::Application::Plugin::Eparam::ocode = 'euc-jp';
    }

=head2 in SubClass

    package WebApp::Pages::Public
    sub setup {
            $CGI::Application::Plugin::Eparam::icode = 'sjis';
            $CGI::Application::Plugin::Eparam::ocode = 'euc-jp';
    }
    package WebApp::Pages::Admin
    sub setup {
            $CGI::Application::Plugin::Eparam::icode = 'euc-jp';
            $CGI::Application::Plugin::Eparam::ocode = 'euc-jp';
    }

=head2 in Method

    package WebApp::Pages::User::Mailform
    sub mailform {

            # &#12371;&#12398;&#22580;&#21512;&#22793;&#25563;&#12399;&#34892;&#12431;&#12428;&#12414;&#12379;&#12435;
            $CGI::Application::Plugin::Eparam::icode = 'jis';
            $CGI::Application::Plugin::Eparam::ocode = 'jis';

            # &#12513;&#12540;&#12523;&#12398;&#20214;&#21517;&#12395;&#12375;&#12383;&#12356;&#37096;&#20998;&#12384;&#12369;&#12434;jis&#12391;&#24471;&#12427;&#12424;&#12358;&#12394;&#20107;&#12364;&#20986;&#26469;&#12414;&#12377;
            $CGI::Application::Plugin::Eparam::icode = 'sjis';
            $CGI::Application::Plugin::Eparam::ocode = 'jis';

    }

=head2 in Part

    package Myapplication::Pages::User::Mailform
    sub mailform {

            # &#19968;&#26178;&#30340;&#12395;&#35373;&#23450;&#12434;&#22793;&#26356;&#12377;&#12427;&#20107;&#12364;&#20986;&#26469;&#12414;&#12377;
            $CGI::Application::Plugin::Eparam::temp_icode = 'sjis';
            $CGI::Application::Plugin::Eparam::temp_ocode = 'jis';
            my $val_jis = $self->eparam('val');
            # undef&#12391;&#20803;&#12395;&#25147;&#12379;&#12414;&#12377;
            undef $CGI::Application::Plugin::Eparam::temp_icode;
            undef $CGI::Application::Plugin::Eparam::temp_ocode;
            my $val_sjis = $self->eparam('val');

    }

=head2 Convert Logic Customize

    # &#33258;&#20998;&#12391;&#22793;&#25563;&#12525;&#12472;&#12483;&#12463;&#12434;&#32068;&#12416;&#20107;&#12364;&#20986;&#26469;&#12414;&#12377;
    $CGI::Application::Plugin::Eparam::econv = sub {
            my $textref = shift; 
            my $ocode = shift;   # output character code
            my $icode = shift;   # input  character code
            # some logic
            Encode::from_to($$textref, 'Guess', $ocode);
    };
    # temp_&#12434;&#20351;&#12358;&#12392;&#19968;&#26178;&#30340;&#12394;&#12418;&#12398;&#12395;&#12394;&#12426;&#12414;&#12377;
    $CGI::Application::Plugin::Eparam::temp_econv = sub {
            my $textref = shift; 
            my $ocode = shift;   # output character code
            my $icode = shift;   # input  character code
            # some logic
            Encode::from_to($$textref, 'Guess', $ocode);
    };
    # undef&#12391;&#20803;&#12395;&#25147;&#12375;&#12414;&#12377;
    undef $CGI::Application::Plugin::Eparam::temp_econv;

=head1 SEE ALSO

L<CGI::Application>

=head1 AUTHOR

Shinichiro Aska

=cut
